#! /data/data/com.termux/files/usr/bin/bash
# TODO: add ability to download updates from git

log="install-script-log.log"
truncate --size 0 "$log"

# small function to improve logging and cleaner code
LogAndExecute() {
  echo "$ $@" >>"$log"
  "$@" >>"$log"
}

trap 'echo "Error while installing dependencies, check the log"; exit 1' ERR INT
echo "Installing dependencies..."
LogAndExecute("apt-get update")
LogAndExecute("apt-get install -y python jq ffmpeg git termux-api")
LogAndExecute("pip install --upgrade -q pip youtube-dl")
echo "Install the Termux:API app to get download notifications."

trap - ERR INT

[[ -d ~/bin ]] || mkdir ~/bin
if ! { echo "$PATH" | grep -q '/com.termux/files/home/bin'; }; then
  echo "Adding $HOME/bin to the PATH"
  cat >>~/.bashrc << EOF
if [[ -d ~/bin ]]; then
  PATH=~/bin:"$PATH"
fi
EOF
fi

echo "Installing symlinks"
ln --symbolic --relative --backup=simple ~/termux-url-script/termux-url-opener ~/bin/termux-url-opener
ln --symbolic --relative --backup=simple ~/termux-url-script/termux-url-opener ~/bin/termux-file-editor
echo "Done"
